# -*- coding: utf-8 -*-
"""Sample_CodeLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WcskZ1ilZsG_CwbKjDoxFIqtbDd41y-g?resourcekey=0-TR_e0wXPzTAH3jvLC3Y9Zg
"""

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet google-genai pillow

"""### Authenticate your notebook environment (Colab only)

If you're running this notebook on Google Colab, run the cell below to authenticate your environment.
"""

import sys

if "google.colab" in sys.modules:
    from google.colab import auth

    auth.authenticate_user()

"""### Configure Google Cloud Project

To use Vertex AI, you need a Google Cloud project with the [Vertex AI API enabled](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).

For more details, see the documentation on [setting up a project and development environment](https://cloud.google.com/vertex-ai/docs/start/cloud-environment).
"""

# Use the environment variable if the user doesn't provide Project ID.
import os

# fmt: off
PROJECT_ID = ""  # @param {type: "string", placeholder: "[your-project-id]", isTemplate: true}
# fmt: on
if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    PROJECT_ID = str(os.environ.get("GOOGLE_CLOUD_PROJECT"))

LOCATION = "global"

from google import genai

client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

"""### Do the required imports"""

import io

from IPython.display import display
from PIL import Image
from google.genai import types

import base64
import time
from IPython.display import Video, Markdown

"""### Helper Functions and Utilities

This section contains the helper functions that will be used throughout the notebook to streamline image generation and processing tasks.
"""

video_model = "veo-3.1-generate-preview"
gemini_model = "gemini-2.5-flash"

def show_video(video):
    if isinstance(video, str):
        file_name = video.split("/")[-1]
        !gsutil cp {video} {file_name}
        display(Video(file_name, embed=True, width=600, height=400))
    else:
        with open("sample.mp4", "wb") as out_file:
            out_file.write(video)
        display(Video("sample.mp4", embed=True, width=600, height=400))

"""## Scene Generation with Gemini

# Generate the script with Gemini

It is very important to detail the characters and the scenes
Let's generate the script from the image?
"""

from google import genai
from google.genai import types
import base64
import os

def generate():

  file_path = '/content/view1.jpeg'

  with open(file_path, 'rb') as file:
      # .read() loads the entire file into memory as a 'bytes' object
      image_bytes = file.read()

  image1 = types.Part.from_bytes(
    data=image_bytes,
    mime_type="image/png",
  )


  prompt = """Generate detailed character profile and scene details to create
    a 8 second video talking about Agent Development Kit (ADK) is a flexible and modular
    framework for developing and deploying AI agents. While optimized for
    Gemini and the Google ecosystem, ADK is model-agnostic, deployment-agnostic,
    and is built for compatibility with other frameworks. ADK was designed to make
    agent development feel more like software development, to make it easier
    for developers to create, deploy, and orchestrate agentic architectures
    that range from simple tasks to complex workflows.

. Provide the response as Markdown. Do not
    use tables in the output. For each character generate a Name, Role,
    Appearance, Personality and Wardrobe"""

  model = "gemini-2.5-flash"
  contents = [
    types.Content(
      role="user",
      parts=[
        image1,
        types.Part.from_text(text=prompt)
      ]
    )
  ]
  tools = [
    types.Tool(google_search=types.GoogleSearch()),
  ]

  generate_content_config = types.GenerateContentConfig(
    temperature = 1,
    top_p = 0.95,
    max_output_tokens = 65535,
    safety_settings = [types.SafetySetting(
      category="HARM_CATEGORY_HATE_SPEECH",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_DANGEROUS_CONTENT",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_HARASSMENT",
      threshold="OFF"
    )],
    tools = tools
  )

  response = client.models.generate_content(
    model = model,
    contents = contents,
    config = generate_content_config,
    )
  return(response.candidates[0].content.parts[0].text)


scene = generate()

display(Markdown(scene))

"""📌 Make sure to review the content generated by Gemini and tweak it to match your narrative and ideas

Create a prompt with the scene and the image generated
"""

gemini_prompt = f"""
You are an expert prompt engineer for Google's Veo model. Analyze the provided
image and combine its content with the provided scene. Make sure to retain the
character identities. Integrate the image's
subject and scene with the requested motion and audio effects.
The final output must be ONLY the prompt itself,
with no preamble. Scene: {",".join(scene)}
"""
with open("/content/view1.jpeg", "rb") as f:
    image = f.read()

response = client.models.generate_content(
    model=gemini_model,
    contents=[gemini_prompt, types.Part.from_bytes(data=image, mime_type="image/png")],
)

# Set Gemini's response in a prompt variable
prompt = response.text
display(Markdown(response.text))

"""📌 Make sure to review the prompt generated by Gemini and tweak it to match your narrative and ideas

# Generate the video with Veo3

Generate the video with the prompt and a reference image
"""

# prompt = types.SubjectReferenceImageDict
enhance_prompt = True  # @param {type: 'boolean'}
generate_audio = True  # @param {type: 'boolean'}

operation = client.models.generate_videos(
    model=video_model,
    prompt=prompt,
    config=types.GenerateVideosConfig(
        reference_images=[
            types.VideoGenerationReferenceImage(
                image=types.Image.from_file(location="/content/view1.jpeg"),
                reference_type="asset",
            )
        ],
        aspect_ratio="16:9",
        number_of_videos=1,
        duration_seconds=8,
        resolution="1080p",
        person_generation="allow_adult",
        enhance_prompt=enhance_prompt,
        generate_audio=generate_audio,
    ),
)

while not operation.done:
    time.sleep(15)
    operation = client.operations.get(operation)
    print(operation)

if operation.response:
    show_video(operation.result.generated_videos[0].video.video_bytes)